# Generated by Django 3.2.3 on 2021-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.FloatField(default=0)),
                ('end', models.FloatField(null=True)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
